export const Actions = {
  SET_EVENT_NAME: "SET_EVENT_NAME",
  SET_EVENT_DISC: "SET_EVENT_DISC",
  SET_EVENT_DATE: "SET_EVENT_DATE",
  SET_EVENT_AGE: "SET_EVENT_AGE",
  SET_EVENT_IMG: "SET_EVENT_IMG",
  CHECK_NAME_FIELD: "CHECK_NAME_FIELD",
  CHECK_DISC_FIELD: "CHECK_DISC_FIELD",
  CHECK_DATE_FIELD: "CHECK_DATE_FIELD",
  CHECK_AGE_FIELD: "CHECK_AGE_FIELDS",
  CHECK_IMG_UPLOADED: "CHECK_IMG_UPLOADED",
};
