export const Actions = {
  SET_STYLE:"SET_STYLE",
  CHECK_USER_VALID:"CHECK_USER_VALID",
  CHECK_EMAIL_VALID:"CHECK_EMAIL_VALID",
  CHECK_PASS_VALID:"CHECK_PASS_VALID",
  GET_USERNAME:"GET_USERNAME",
  GET_EMAIL:"GET_EMAIL",
  GET_PASS:"GET_PASS",
  SET_ERROR:"SET_ERROR"
}