export const ActionForEventCard = {
  SET_CHANGED_EVENT: "SET_CHANGED_EVENT",
  SET_NEWDATE_EVENT: "SET_NEW_DATE",
  SET_NEWAGE_EVENT: "SET_NEWAGE_EVENT",
  SET_NEWDISC_EVENT: "SET_NEWDISC_EVENT",
  SET_NEWNAME_EVENT: "SET_NEWNAME_EVENT",
  SET_NEWIMG_EVENT: "SET_NEWIMG_EVENT",
  SET_STYLE_FOR_BG: "SET_STYLE_FOR_BG",
  SET_TRANSFORM_CARD_IN_EDIT_MODE: "SET_TRANSFORM_CARD_IN_EDIT_MODE",
  SET_DOUBLECHECK_MENU: "SET_DOUBLECHECK_MENU",
  SHOW_BOOK_EVENT_BUTTON: "SHOW_BOOK_EVENT_BUTTON",
};
